"""Tests for compose file generation."""

import os
from unittest.mock import patch

os.environ.setdefault("CASHPILOT_API_KEY", "test-fleet-key")

import pytest
import yaml

from app import compose_generator


def _mock_service(
    slug="honeygain",
    name="Honeygain",
    image="honeygain/honeygain:latest",
    env=None,
    ports=None,
    volumes=None,
    category="bandwidth",
    network_mode=None,
    cap_add=None,
    command=None,
):
    svc = {
        "name": name,
        "slug": slug,
        "category": category,
        "status": "active",
        "description": "Test service",
        "docker": {
            "image": image,
            "env": env or [],
            "ports": ports or [],
            "volumes": volumes or [],
        },
    }
    if network_mode:
        svc["docker"]["network_mode"] = network_mode
    if cap_add:
        svc["docker"]["cap_add"] = cap_add
    if command:
        svc["docker"]["command"] = command
    return svc


class TestServiceToCompose:
    def test_basic_service(self):
        svc = _mock_service()
        result = compose_generator._service_to_compose(svc)
        assert result is not None
        assert result["image"] == "honeygain/honeygain:latest"
        assert result["container_name"] == "cashpilot-honeygain"
        assert result["restart"] == "unless-stopped"

    def test_no_image_returns_none(self):
        svc = _mock_service(image="")
        svc["docker"]["image"] = ""
        result = compose_generator._service_to_compose(svc)
        assert result is None

    def test_no_docker_returns_none(self):
        svc = {"name": "No Docker", "slug": "nodock", "docker": {}}
        result = compose_generator._service_to_compose(svc)
        assert result is None

    def test_env_vars_included(self):
        svc = _mock_service(
            env=[
                {"key": "EMAIL", "default": "user@example.com"},
                {"key": "PASSWORD", "default": ""},
            ]
        )
        result = compose_generator._service_to_compose(svc)
        assert "EMAIL" in result["environment"]
        assert result["environment"]["EMAIL"] == "user@example.com"

    def test_env_override(self):
        svc = _mock_service(env=[{"key": "EMAIL", "default": "default@x.com"}])
        result = compose_generator._service_to_compose(svc, env_vars={"EMAIL": "custom@y.com"})
        assert result["environment"]["EMAIL"] == "custom@y.com"

    def test_hostname_substitution(self):
        svc = _mock_service(env=[{"key": "DEVICE_NAME", "default": "{hostname}"}])
        result = compose_generator._service_to_compose(svc, hostname="myhost")
        assert result["environment"]["DEVICE_NAME"] == "myhost"

    def test_ports_included(self):
        svc = _mock_service(ports=["28967:28967/tcp"])
        result = compose_generator._service_to_compose(svc)
        assert "28967:28967/tcp" in result["ports"]

    def test_volumes_included(self):
        svc = _mock_service(volumes=["/data/storj:/app/config"])
        result = compose_generator._service_to_compose(svc)
        assert "/data/storj:/app/config" in result["volumes"]

    def test_network_mode(self):
        svc = _mock_service(network_mode="host")
        result = compose_generator._service_to_compose(svc)
        assert result["network_mode"] == "host"

    def test_cap_add(self):
        svc = _mock_service(cap_add=["NET_ADMIN"])
        result = compose_generator._service_to_compose(svc)
        assert result["cap_add"] == ["NET_ADMIN"]

    def test_command(self):
        svc = _mock_service(command="/entrypoint.sh --arg")
        result = compose_generator._service_to_compose(svc)
        assert result["command"] == "/entrypoint.sh --arg"

    def test_required_env_placeholder(self):
        svc = _mock_service(env=[{"key": "TOKEN", "default": "", "required": True, "label": "API Token"}])
        result = compose_generator._service_to_compose(svc)
        assert result["environment"]["TOKEN"] == "<API Token>"

    def test_labels_included(self):
        svc = _mock_service()
        result = compose_generator._service_to_compose(svc)
        assert result["labels"]["cashpilot.managed"] == "true"
        assert result["labels"]["cashpilot.service"] == "honeygain"


class TestGenerateComposeSingle:
    def test_generates_valid_yaml(self):
        svc = _mock_service()
        with patch("app.compose_generator.get_service", return_value=svc):
            output = compose_generator.generate_compose_single("honeygain")
        assert "Generated by CashPilot" in output
        # Parse YAML (skip the comment header)
        lines = [line for line in output.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(lines))
        assert "services" in parsed

    def test_unknown_service_raises(self):
        with (
            patch("app.compose_generator.get_service", return_value=None),
            pytest.raises(ValueError, match="Unknown service"),
        ):
            compose_generator.generate_compose_single("nope")

    def test_no_image_raises(self):
        svc = {"name": "No Image", "slug": "noimg", "docker": {}}
        with (
            patch("app.compose_generator.get_service", return_value=svc),
            pytest.raises(ValueError, match="no Docker image"),
        ):
            compose_generator.generate_compose_single("noimg")


class TestGenerateComposeMulti:
    def test_generates_multi(self):
        svc1 = _mock_service("svc1", "Service 1")
        svc2 = _mock_service("svc2", "Service 2", image="img2:latest")

        def mock_get(slug):
            return {"svc1": svc1, "svc2": svc2}.get(slug)

        with patch("app.compose_generator.get_service", side_effect=mock_get):
            output = compose_generator.generate_compose_multi(["svc1", "svc2"])
        assert "cashpilot-svc1" in output
        assert "cashpilot-svc2" in output

    def test_empty_list_raises(self):
        with (
            patch("app.compose_generator.get_service", return_value=None),
            pytest.raises(ValueError, match="No deployable"),
        ):
            compose_generator.generate_compose_multi(["nonexistent"])


class TestGenerateComposeAll:
    def test_generates_all(self):
        svcs = [
            _mock_service("a", "A"),
            _mock_service("b", "B", image="b:latest"),
        ]
        with (
            patch("app.compose_generator.get_services", return_value=svcs),
            patch(
                "app.compose_generator.get_service",
                side_effect=lambda s: next((x for x in svcs if x["slug"] == s), None),
            ),
        ):
            output = compose_generator.generate_compose_all()
        assert "cashpilot-a" in output
        assert "cashpilot-b" in output


class TestDeadServicesAreNotExported:
    """A compose file is a runnable artifact: exporting one for a dead service
    points the user at something that cannot earn (Presearch shut down July
    2026 and its entry stays in the catalog as status: dead)."""

    def _dead(self):
        svc = _mock_service(slug="presearch", name="Presearch", image="presearch/node")
        svc["status"] = "dead"
        return svc

    def test_single_export_of_a_dead_service_refuses(self):
        with (
            patch("app.compose_generator.get_service", return_value=self._dead()),
            pytest.raises(ValueError, match="no longer available"),
        ):
            compose_generator.generate_compose_single("presearch")

    def test_multi_export_skips_dead_services(self):
        live = _mock_service(slug="honeygain", name="Honeygain")

        def mock_get(slug):
            return {"presearch": self._dead(), "honeygain": live}.get(slug)

        with patch("app.compose_generator.get_service", side_effect=mock_get):
            output = compose_generator.generate_compose_multi(["presearch", "honeygain"])
        assert "cashpilot-honeygain" in output  # negative control: live stays
        assert "presearch" not in output

    def test_the_real_dead_presearch_is_not_in_export_all(self):
        # Against the real catalog: the entry exists with an image, and must
        # still not be exported.
        from app.catalog import load_services

        presearch = next(s for s in load_services() if s.get("slug") == "presearch")
        assert presearch["status"] == "dead"
        assert presearch["docker"]["image"]  # the trap: image present, status dead
        out = compose_generator.generate_compose_all()
        assert "presearch" not in out


class TestEscapeInterpolation:
    def test_basic_escape(self):
        assert compose_generator._escape_interpolation("${FOO}") == "$${FOO}"

    def test_no_vars_unchanged(self):
        assert compose_generator._escape_interpolation("no-vars-here") == "no-vars-here"

    def test_already_escaped_not_doubled(self):
        assert compose_generator._escape_interpolation("$${ALREADY}") == "$${ALREADY}"

    def test_multiple_vars(self):
        result = compose_generator._escape_interpolation("${A} and ${B}")
        assert result == "$${A} and $${B}"

    def test_mixed_escaped_and_unescaped(self):
        result = compose_generator._escape_interpolation("$${OK} ${NEEDS_ESCAPE}")
        assert result == "$${OK} $${NEEDS_ESCAPE}"

    def test_empty_string(self):
        assert compose_generator._escape_interpolation("") == ""


class TestIsNamedVolume:
    def test_named_volume(self):
        assert compose_generator._is_named_volume("myvolume:/data") == "myvolume"

    def test_absolute_path(self):
        assert compose_generator._is_named_volume("/host/path:/data") is None

    def test_relative_path(self):
        assert compose_generator._is_named_volume("./relative:/data") is None

    def test_home_path(self):
        assert compose_generator._is_named_volume("~/home:/data") is None

    def test_empty_string(self):
        assert compose_generator._is_named_volume("") is None

    def test_no_colon(self):
        assert compose_generator._is_named_volume("myvolume") == "myvolume"


class TestNamedVolumeDeclaration:
    def test_named_volumes_declared_at_top_level(self):
        svc = _mock_service(volumes=["mydata:/app/data"])
        with patch("app.compose_generator.get_service", return_value=svc):
            output = compose_generator.generate_compose_single("honeygain")
        lines = [line for line in output.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(lines))
        assert "volumes" in parsed
        assert "mydata" in parsed["volumes"]

    def test_bind_mounts_no_top_level_volumes(self):
        svc = _mock_service(volumes=["/host/path:/container/path"])
        with patch("app.compose_generator.get_service", return_value=svc):
            output = compose_generator.generate_compose_single("honeygain")
        lines = [line for line in output.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(lines))
        assert "volumes" not in parsed or parsed.get("volumes") is None


class TestResourceLimitsSurviveExport:
    """CashPilot-65q4: the export dropped the whole docker.resources block.

    A user exporting storj to Portainer got a container without its memory
    ceiling, OOM bias or CPU weight — silently less protected than the same
    service deployed by the worker. Compose accepts all four keys top-level
    under the catalog's own names.
    """

    def _compose_for(self, resources):
        svc = _mock_service(slug="storj", name="Storj", image="storjlabs/storagenode")
        if resources is not None:
            svc["docker"]["resources"] = resources
        return compose_generator._service_to_compose(svc)

    def test_all_declared_limits_are_emitted(self):
        block = self._compose_for(
            {"mem_limit": "2g", "mem_reservation": "1g", "oom_score_adj": -100, "cpu_shares": 4096}
        )
        assert block["mem_limit"] == "2g"
        assert block["mem_reservation"] == "1g"
        assert block["oom_score_adj"] == -100
        assert block["cpu_shares"] == 4096

    def test_only_the_keys_the_catalog_sets_are_emitted(self):
        block = self._compose_for({"mem_limit": "2g"})
        assert block["mem_limit"] == "2g"
        for absent in ("mem_reservation", "oom_score_adj", "cpu_shares"):
            assert absent not in block, f"{absent} was invented out of nothing"

    def test_a_service_without_resources_emits_none(self):
        # Negative control: absence stays absence.
        block = self._compose_for(None)
        for key in ("mem_limit", "mem_reservation", "oom_score_adj", "cpu_shares"):
            assert key not in block

    def test_a_truthy_non_mapping_resources_value_is_ignored(self):
        # A malformed catalog entry (resources as a list) must not crash the
        # export nor leak anything into the block — same outcome as absence.
        block = self._compose_for(["invalid"])
        for key in ("mem_limit", "mem_reservation", "oom_score_adj", "cpu_shares"):
            assert key not in block

    def test_the_real_storj_export_carries_its_limits(self):
        # Against the real catalog, end to end through the YAML renderer.
        import yaml as _yaml

        from app.catalog import load_services

        storj = next(s for s in load_services() if s.get("slug") == "storj")
        with patch("app.compose_generator.get_service", return_value=storj):
            output = compose_generator.generate_compose_single("storj")
        parsed = _yaml.safe_load("\n".join(line for line in output.split("\n") if not line.startswith("#")))
        svc = parsed["services"]["cashpilot-storj"]
        assert svc["mem_limit"] == "2g"
        assert svc["oom_score_adj"] == -100
        assert svc["cpu_shares"] == 4096


class TestCommandAndVolumeSubstitution:
    """The exporter must FILL ${KEY} placeholders the way the worker deploy does.

    Before this existed, the exporter only ESCAPED them, so an exported file for
    every argument-auth service (honeygain, iproyal, traffmonetizer, packetshare,
    proxybase) ran the client with the literal string "${EMAIL}" as its
    credential — a compose file that could never authenticate (issue #343).
    """

    def test_command_placeholders_are_filled_from_supplied_values(self):
        svc = _mock_service(
            env=[
                {"key": "ID", "required": True, "label": "Access Token"},
                {"key": "NAME", "default": "dev-{hostname}"},
            ],
            command="${ID} ${NAME}",
        )
        result = compose_generator._service_to_compose(svc, env_vars={"ID": "tok123", "NAME": "mydev"})
        assert result["command"] == "tok123 mydev"

    def test_command_placeholders_fall_back_to_defaults_and_labels(self):
        svc = _mock_service(
            env=[
                {"key": "ID", "required": True, "label": "Access Token"},
                {"key": "NAME", "default": "dev-{hostname}"},
            ],
            command="${ID} ${NAME}",
        )
        result = compose_generator._service_to_compose(svc, hostname="pi4")
        assert result["command"] == "<Access Token> dev-pi4"

    def test_unknown_placeholder_is_still_escaped_for_compose(self):
        # proxyrack's default carries ${UUID}, which is no catalog env key —
        # values CashPilot does not hold keep the escape-as-template behavior.
        svc = _mock_service(command="start ${NOT_A_CATALOG_KEY}")
        result = compose_generator._service_to_compose(svc)
        assert result["command"] == "start $${NOT_A_CATALOG_KEY}"

    def test_volume_host_paths_are_filled_from_supplied_values(self):
        svc = _mock_service(
            env=[{"key": "IDENTITY_DIR", "required": True, "label": "Identity Directory"}],
            volumes=["${IDENTITY_DIR}:/app/identity"],
        )
        result = compose_generator._service_to_compose(svc, env_vars={"IDENTITY_DIR": "/mnt/id"})
        assert result["volumes"] == ["/mnt/id:/app/identity"]

    def test_the_real_proxybase_export_authenticates_not_placeholders(self):
        # End to end through the YAML renderer against the real catalog entry:
        # the peer client reads ONLY positional arguments (its env-var hint is
        # false — verified live against the pinned digest and tag v2.0.3), so
        # the exported command must carry the actual values.
        from app.catalog import load_services

        proxybase = next(s for s in load_services() if s.get("slug") == "proxybase")
        with patch("app.compose_generator.get_service", return_value=proxybase):
            output = compose_generator.generate_compose_single("proxybase", env_vars={"ID": "tok123", "NAME": "mydev"})
        parsed = yaml.safe_load("\n".join(line for line in output.split("\n") if not line.startswith("#")))
        assert parsed["services"]["cashpilot-proxybase"]["command"] == "tok123 mydev"
        assert "${ID}" not in output

    def test_a_credential_containing_a_dollar_survives_compose_interpolation(self):
        # Compose interpolates $VAR inside unquoted/double-quoted YAML values,
        # so a password like tok$word emitted verbatim silently CHANGES when the
        # exported file runs. $$ is the spec's literal form — assert on it.
        svc = _mock_service(
            env=[{"key": "ID", "required": True, "label": "Access Token"}],
            command="${ID} fixed",
        )
        result = compose_generator._service_to_compose(svc, env_vars={"ID": "tok$word"})
        assert result["command"] == "tok$$word fixed"
        assert result["environment"]["ID"] == "tok$$word"

    def test_dollar_escape_applies_to_volume_paths_too(self):
        svc = _mock_service(
            env=[{"key": "IDENTITY_DIR", "required": True, "label": "Identity Directory"}],
            volumes=["${IDENTITY_DIR}:/app/identity"],
        )
        result = compose_generator._service_to_compose(svc, env_vars={"IDENTITY_DIR": "/mnt/$data"})
        assert result["volumes"] == ["/mnt/$$data:/app/identity"]

    def test_a_value_that_itself_looks_like_a_placeholder_is_not_reinterpolated(self):
        # The value escapes BEFORE the general escape pass, so its ${ arrives
        # already $-prefixed and the pass leaves it alone: one escape, not two.
        svc = _mock_service(
            env=[{"key": "ID", "required": True, "label": "Access Token"}],
            command="${ID}",
        )
        result = compose_generator._service_to_compose(svc, env_vars={"ID": "we${ird}"})
        assert result["command"] == "we$${ird}"

    def test_the_real_honeygain_export_carries_credentials(self):
        from app.catalog import load_services

        honeygain = next(s for s in load_services() if s.get("slug") == "honeygain")
        with patch("app.compose_generator.get_service", return_value=honeygain):
            output = compose_generator.generate_compose_single(
                "honeygain",
                env_vars={
                    "HONEYGAIN_EMAIL": "a@b.c",
                    "HONEYGAIN_PASSWORD": "pw",
                    "HONEYGAIN_DEVICE_NAME": "dev1",
                },
            )
        parsed = yaml.safe_load("\n".join(line for line in output.split("\n") if not line.startswith("#")))
        cmd = parsed["services"]["cashpilot-honeygain"]["command"]
        assert "-email a@b.c" in cmd
        assert "${HONEYGAIN_EMAIL}" not in cmd
