"""CashPilot-gan, part two: eleven top-level pages, and a build that ran too late.

The first half of this bead fixed the orphaned guide and generated the guide nav
from the catalog. Two things were left:

* **Eleven flat top-level entries.** With ``navigation.tabs`` enabled, every one
  of them is a TAB across the header, so the site opened with eleven tabs and no
  order a reader could reason about — "Network Isolation" sitting as a peer of
  "Home".
* **The site was only ever built on push to main.** ``mkdocs gh-deploy --force``
  was the first thing to evaluate the nav, so a nav entry pointing at a file
  that did not exist was discovered by publishing it.

WHAT COMPARABLE PROJECTS ACTUALLY DO, since the bead asked for research first:

* **Paperless-ngx** (Material/Zensical, closest in size) keeps eleven top-level
  entries almost flat, with ONE nested group, and orders them as a journey:
  index, setup, usage, configuration, Administration, advanced usage, api,
  development, faq, troubleshooting, changelog.
* **Immich** (Docusaurus, autogenerated from the filesystem): overview, install,
  features, administration, guides, developer, api, FAQ.
* **Authentik** (Docusaurus): core, install-config, add-secure-apps, customize,
  sys-mgmt, security, troubleshooting, releases, enterprise, developer-docs.

Three things are consistent across all of them, and none of them is the
"Start here / Run it / Operate it" shape the bead sketched:

1. Order follows the reader's journey — learn, install, use, configure, operate,
   reference — rather than alphabetical or arbitrary.
2. Section names are domain nouns (Install, Administration, Security,
   Reference), not imperative task labels.
3. Nothing is nested alone. A group exists because it has siblings.

So the nav groups by domain, in journey order, and every group has at least two
children.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
MKDOCS = ROOT / "mkdocs.yml"
DOCS = ROOT / "docs"
WORKFLOW = ROOT / ".github" / "workflows" / "docs.yml"


def nav_text() -> str:
    text = MKDOCS.read_text(encoding="utf-8")
    start = text.index("\nnav:")
    # Ends at the next top-level key, which is the first column-0 line after nav.
    rest = text[start + 1 :]
    match = re.search(r"\n(?=[A-Za-z_])", rest)
    return rest[: match.start()] if match else rest


def top_level() -> list[str]:
    """The entries that become TABS. Two-space indent, nothing deeper."""
    return [line.strip()[2:].split(":")[0].strip() for line in nav_text().splitlines() if re.match(r"^  - \S", line)]


class TestTheTopLevelIsGroupedRatherThanFlat:
    def test_there_are_far_fewer_tabs_than_before(self):
        """Eleven was the measured starting point; the fix is meaningless if the
        count did not actually come down."""
        assert len(top_level()) <= 8, f"{len(top_level())} tabs: {top_level()}"

    def test_the_groups_are_domain_nouns(self):
        """What Paperless, Immich and Authentik all do. Imperative labels
        ("Run it") were the sketch in the bead and are not what anyone ships."""
        names = top_level()
        for expected in ("Configuration", "Security", "Operations", "Reference"):
            assert expected in names, f"{expected} is not a top-level section: {names}"

    def test_home_and_getting_started_come_first(self):
        """Journey order. A reader who has never run it needs those two before
        anything else."""
        names = top_level()
        assert names[0] == "Home"
        assert names[1] == "Getting Started"

    def test_the_service_guides_are_near_the_top(self):
        """They are the reason most visitors arrive — 50 of the site's ~62
        pages. Third, straight after Getting Started."""
        assert top_level()[2] == "Service Guides"

    def test_reference_comes_last(self):
        """Architecture and the roadmap are the least likely first stop."""
        assert top_level()[-1] == "Reference"

    def test_no_section_holds_a_single_page(self):
        """A group of one is a rename with extra clicks, not a grouping."""
        text = nav_text()
        groups: dict[str, int] = {}
        current = None
        for line in text.splitlines():
            if re.match(r"^  - [^:]+:\s*$", line):  # a group header has no value
                current = line.strip()[2:].rstrip(":")
                groups[current] = 0
            elif re.match(r"^  - \S", line):
                current = None
            elif current and re.match(r"^    - \S", line):
                groups[current] += 1
        lonely = [name for name, count in groups.items() if count == 1]
        assert not lonely, f"sections holding a single page: {lonely}"


class TestNoPageIsLostInTheMove:
    def test_every_page_that_was_in_the_nav_still_is(self):
        """The restructure moved eleven entries. Losing one would orphan a page
        as silently as the guide this bead started with."""
        refs = set(re.findall(r": ([\w./-]+\.md)", nav_text()))
        for page in (
            "index.md",
            "getting-started.md",
            "architecture.md",
            "configuration.md",
            "roadmap.md",
            "security-defaults.md",
            "isolation.md",
            "fleet.md",
            "backup.md",
            "guides/prometheus-metrics.md",
            "upgrade-v1.md",
        ):
            assert page in refs, f"{page} fell out of the nav"

    def test_the_research_pages_are_no_longer_orphans(self):
        """Both were reachable only by URL. They are real reference material —
        the measurements behind catalog thresholds — not drafts."""
        refs = set(re.findall(r": ([\w./-]+\.md)", nav_text()))
        assert "research/idle-network-traffic.md" in refs
        assert "research/per-ip-device-limits.md" in refs

    def test_every_page_in_the_nav_exists_on_disk(self):
        """--strict fails the build on this; catching it here is cheaper."""
        missing = [ref for ref in re.findall(r": ([\w./-]+\.md)", nav_text()) if not (DOCS / ref).is_file()]
        assert not missing, f"nav points at files that do not exist: {missing}"


class TestTheDocsBuildRunsBeforeMergeNotAfter:
    def _doc(self) -> dict:
        # `on:` is parsed by PyYAML 1.1 rules as the boolean True.
        return yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))

    def _triggers(self) -> dict:
        doc = self._doc()
        return doc.get("on") or doc.get(True)

    def test_it_runs_on_pull_requests(self):
        """The whole point: `mkdocs gh-deploy` on main used to be the first
        thing that evaluated the nav."""
        assert "pull_request" in self._triggers()

    def test_the_pr_build_is_strict(self):
        """Without --strict, a nav entry pointing at a missing file is a
        WARNING and the build still passes.

        Scoped to the BUILD job's steps, not to every job's. Searching the whole
        workflow would keep passing if the strict build were moved into `deploy`
        — which runs only on main, and is precisely the regression that puts the
        gate back after the merge instead of before it. (CodeRabbit, PR #257.)
        """
        runs = [step.get("run", "") for step in self._doc()["jobs"]["build"]["steps"] if isinstance(step, dict)]
        assert any("mkdocs build --strict" in run for run in runs), runs

    def test_the_deploy_waits_for_the_build(self):
        """Otherwise the check is decorative: main could deploy a site the
        build job was still failing on."""
        deploy = self._doc()["jobs"]["deploy"]
        needs = deploy.get("needs")
        needs = [needs] if isinstance(needs, str) else (needs or [])
        assert "build" in needs, f"deploy needs {needs!r}"

    def test_the_deploy_does_not_run_on_a_pull_request(self):
        """A fork PR must never be able to publish to the site.

        The EXACT condition, not a substring. `"push" in condition` is satisfied
        by `github.event_name != 'push'` too — an inversion that would deploy on
        every pull request and on nothing else.
        """
        condition = str(self._doc()["jobs"]["deploy"].get("if", "")).strip()
        assert condition == "github.event_name == 'push'", f"deploy `if:` is {condition!r}"

    def test_only_the_deploy_job_can_write(self):
        """Least privilege: the PR build needs to read the checkout and nothing
        more, and it is the job a fork can trigger.

        The exact maps, because a permissions block that GAINED a write scope
        (`packages: write`, say) would satisfy a check that only looked at
        `contents`.
        """
        doc = self._doc()
        assert doc["permissions"] == {"contents": "read"}, doc["permissions"]
        assert doc["jobs"]["deploy"]["permissions"] == {"contents": "write"}, doc["jobs"]["deploy"]["permissions"]
        assert "permissions" not in doc["jobs"]["build"], "the build job declares its own permissions"
