"""Scaffold a new service from its YAML (CashPilot-9q1).

Adding a service should be one file plus an optional collector. It currently
also means a README table row and a docs/guides page, and every extra place a
contributor has to remember is a place a first-time contributor gets it wrong,
picks up a review comment, and does not come back.

The README half is generated by generate_readme_tables.py. This writes the
guide stub from the same YAML, so the only handwritten thing left is the prose
that genuinely needs a human.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app import catalog  # noqa: E402

TEMPLATE = """# {name}

> **Category:** {category} | **Status:** {status}
> **Website:** [{website}]({website})

## Description

{description}

## Earning Estimates

| Metric | Value |
|--------|-------|
| Monthly range | {earnings} |
| Payout methods | {methods} |
| Minimum payout | {minimum} |

## Requirements

| Requirement | Value |
|-------------|-------|
| Residential IP required | {residential} |
| VPS allowed | {vps} |
| Devices per account | {per_account} |
| Devices per IP | {per_ip} |

## Setup

1. Sign up at [{name}]({signup}).
2. Copy the credentials listed in the service's catalog entry.
3. Deploy from the CashPilot catalog and paste them when prompted.

<!-- Everything above is derived from services/{category}/{slug}.yml.
     Add anything a user genuinely needs a human to explain BELOW this line:
     captcha quirks, account gotchas, what the dashboard calls things. -->
"""


def _fmt(value: object, unknown: str = "Not documented") -> str:
    if value is None:
        return unknown
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if value == 0:
        return "Unlimited"
    return str(value)


def render(slug: str) -> str:
    service = catalog.get_service(slug)
    if not service:
        raise SystemExit(f"No catalog entry for {slug!r}. Write services/<category>/{slug}.yml first.")
    reqs = service.get("requirements") or {}
    earnings = service.get("earnings") or {}
    payment = service.get("payment") or {}
    low, high = earnings.get("monthly_low"), earnings.get("monthly_high")
    return TEMPLATE.format(
        name=service.get("name", slug),
        slug=slug,
        category=service.get("category", ""),
        status=str(service.get("status", "")).title(),
        website=service.get("website", ""),
        description=service.get("description", "").strip(),
        earnings=(f"${low} - ${high} (estimate)" if low is not None and high is not None else "Not documented"),
        methods=", ".join(payment.get("methods") or []) or "Not documented",
        minimum=_fmt(payment.get("minimum_payout")),
        residential=_fmt(reqs.get("residential_ip")),
        vps=_fmt(reqs.get("vps_ip")),
        per_account=_fmt(reqs.get("devices_per_account")),
        per_ip=_fmt(reqs.get("devices_per_ip")),
        signup=(service.get("referral") or {}).get("signup_url") or service.get("website", ""),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("slug")
    parser.add_argument("--force", action="store_true", help="overwrite an existing guide")
    args = parser.parse_args()

    target = ROOT / "docs" / "guides" / f"{args.slug}.md"
    if target.exists() and not args.force:
        print(f"{target} already exists; pass --force to overwrite.", file=sys.stderr)
        return 1
    target.write_text(render(args.slug), encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
